# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(785, 887)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 891))
        self.tabWidget.setStyleSheet("color: rgb(170, 0, 255);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(410, 390, 46, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(210, 420, 181, 171))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(660, 670, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(30, 80, 711, 301))
        self.tableWidget.setRowCount(392)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(610, 400, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 390, 46, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(20, 420, 181, 171))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_4.setGeometry(QtCore.QRect(400, 420, 171, 171))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(230, 390, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(580, 420, 181, 171))
        self.textEdit_3.setObjectName("textEdit_3")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(390, 640, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(400, 610, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 0, 255);")
        self.label.setObjectName("label")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_5.setGeometry(QtCore.QRect(40, 610, 231, 61))
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 690, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(450, 710, 82, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(450, 740, 82, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(300, 640, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(340, 710, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(340, 740, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_7.setObjectName("label_7")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_5.setGeometry(QtCore.QRect(480, 640, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_6.setGeometry(QtCore.QRect(570, 640, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(110, 820, 551, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(290, 610, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(480, 610, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(570, 620, 46, 13))
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(570, 610, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_37.setObjectName("label_37")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 20, 161, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(290, 780, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_16.setObjectName("label_16")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(300, 680, 301, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(520, 710, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(580, 710, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(520, 740, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(580, 740, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Computer_Icon_Pack-03-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 761, 871))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 80, 681, 341))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("color: rgb(255, 0, 127);")
        self.groupBox_9.setObjectName("groupBox_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 90, 131, 41))
        font = QtGui.QFont()
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.textEdit_16 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_16.setGeometry(QtCore.QRect(400, 100, 191, 31))
        self.textEdit_16.setObjectName("textEdit_16")
        self.textEdit_8 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_8.setGeometry(QtCore.QRect(400, 20, 191, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_15 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_15.setGeometry(QtCore.QRect(400, 60, 191, 31))
        self.textEdit_15.setObjectName("textEdit_15")
        self.textEdit_19 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_19.setGeometry(QtCore.QRect(400, 260, 191, 71))
        self.textEdit_19.setObjectName("textEdit_19")
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        self.label_9.setGeometry(QtCore.QRect(310, 30, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(170, 85, 127);\n"
"color: rgb(255, 0, 127);")
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setGeometry(QtCore.QRect(310, 70, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(170, 85, 127);\n"
"color: rgb(255, 0, 127);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setGeometry(QtCore.QRect(320, 110, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(170, 85, 127);\n"
"color: rgb(255, 0, 127);")
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(self.groupBox_9)
        self.label_10.setGeometry(QtCore.QRect(290, 280, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(170, 85, 127);\n"
"color: rgb(255, 0, 127);")
        self.label_10.setObjectName("label_10")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_7.setGeometry(QtCore.QRect(20, 50, 131, 22))
        self.comboBox_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 121, 16))
        font = QtGui.QFont()
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(170, 85, 127);\n"
"color: rgb(255, 0, 127);")
        self.label_14.setObjectName("label_14")
        self.textEdit_9 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_9.setGeometry(QtCore.QRect(400, 180, 191, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_10.setGeometry(QtCore.QRect(400, 140, 191, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_29 = QtWidgets.QLabel(self.groupBox_9)
        self.label_29.setGeometry(QtCore.QRect(320, 150, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_43 = QtWidgets.QLabel(self.groupBox_9)
        self.label_43.setGeometry(QtCore.QRect(320, 190, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.textEdit_11 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_11.setGeometry(QtCore.QRect(400, 220, 191, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.label_44 = QtWidgets.QLabel(self.groupBox_9)
        self.label_44.setGeometry(QtCore.QRect(320, 230, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(60, 20, 601, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 430, 351, 311))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("color: rgb(255, 0, 127);")
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_39 = QtWidgets.QLabel(self.groupBox_10)
        self.label_39.setGeometry(QtCore.QRect(10, 20, 331, 281))
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(370, 430, 371, 311))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("color: rgb(255, 0, 127);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(-40, 20, 401, 271))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 701, 251))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(0, 0, 127);")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 180, 81, 31))
        self.pushButton_7.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_6.setGeometry(QtCore.QRect(210, 20, 461, 201))
        self.textEdit_6.setObjectName("textEdit_6")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(40, 140, 111, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 80, 101, 31))
        self.pushButton_11.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setGeometry(QtCore.QRect(10, 120, 231, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(0, 0, 127);")
        self.label_38.setObjectName("label_38")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_8.setGeometry(QtCore.QRect(30, 50, 121, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(0, 0, 127);")
        self.label_20.setObjectName("label_20")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 310, 701, 221))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color: rgb(0, 0, 127);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(60, 50, 131, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(60, 30, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 127);")
        self.label_11.setObjectName("label_11")
        self.textEdit_13 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_13.setGeometry(QtCore.QRect(370, 20, 191, 41))
        self.textEdit_13.setObjectName("textEdit_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_12.setGeometry(QtCore.QRect(80, 90, 91, 31))
        self.pushButton_12.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(280, 30, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.textEdit_7 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_7.setGeometry(QtCore.QRect(370, 70, 191, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_45 = QtWidgets.QLabel(self.groupBox_3)
        self.label_45.setGeometry(QtCore.QRect(290, 80, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.textEdit_12 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_12.setGeometry(QtCore.QRect(370, 120, 191, 41))
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_17 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_17.setGeometry(QtCore.QRect(370, 170, 191, 41))
        self.textEdit_17.setObjectName("textEdit_17")
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setGeometry(QtCore.QRect(290, 130, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_3)
        self.label_47.setGeometry(QtCore.QRect(290, 180, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setGeometry(QtCore.QRect(60, 20, 601, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 550, 341, 261))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("color: rgb(0, 0, 127);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(-20, 20, 361, 221))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(380, 550, 351, 261))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("color: rgb(0, 0, 127);")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setGeometry(QtCore.QRect(-20, 30, 371, 221))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(60, 10, 601, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 40, 711, 191))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("color: rgb(0, 170, 0);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit_14 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_14.setGeometry(QtCore.QRect(140, 100, 181, 51))
        self.textEdit_14.setObjectName("textEdit_14")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(340, 110, 75, 31))
        font = QtGui.QFont()
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 170, 127);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(140, 60, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(50, 60, 71, 16))
        font = QtGui.QFont()
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(40, 120, 71, 20))
        font = QtGui.QFont()
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_22.setObjectName("label_22")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(30, 550, 381, 231))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(20, 250, 371, 261))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(410, 250, 331, 251))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(420, 550, 331, 291))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(50, 10, 601, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Y Train"))
        self.pushButton.setText(_translate("Dialog", "İŞLEMİ YAP"))
        self.label_5.setText(_translate("Dialog", "Y Test"))
        self.label_2.setText(_translate("Dialog", "X Train"))
        self.label_4.setText(_translate("Dialog", "X Test"))
        self.label.setText(_translate("Dialog", "Test Size"))
        self.pushButton_2.setText(_translate("Dialog", "Dataset Info"))
        self.radioButton.setText(_translate("Dialog", "PCA"))
        self.radioButton_2.setText(_translate("Dialog", "Ki Kare"))
        self.label_6.setText(_translate("Dialog", "Öznitelik Dönüşüm : "))
        self.label_7.setText(_translate("Dialog", "Öznitelik Seçim:"))
        self.label_34.setText(_translate("Dialog", "Sınıflandırma"))
        self.label_35.setText(_translate("Dialog", "KFold N Değeri"))
        self.label_37.setText(_translate("Dialog", "K Fold Seçenek"))
        self.pushButton_3.setText(_translate("Dialog", "VERİ SETİNİ YÜKLE"))
        self.label_16.setText(_translate("Dialog", "Dengeli/Dengesiz İşlem"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "İşlemler"))
        self.groupBox_9.setTitle(_translate("Dialog", "Makine Öğrenmesi Algoritmaları"))
        self.pushButton_10.setText(_translate("Dialog", "Modeli Eğit"))
        self.label_9.setText(_translate("Dialog", "Başarı oranı "))
        self.label_12.setText(_translate("Dialog", " Sensivity"))
        self.label_13.setText(_translate("Dialog", "Specifity"))
        self.label_10.setText(_translate("Dialog", "Karışıklık Matrisi"))
        self.label_14.setText(_translate("Dialog", "Eğitilecek Algoritma"))
        self.label_29.setText(_translate("Dialog", "MSE"))
        self.label_43.setText(_translate("Dialog", "R2"))
        self.label_44.setText(_translate("Dialog", "MAE"))
        self.groupBox_10.setTitle(_translate("Dialog", "ROC EĞRİSİ"))
        self.groupBox_5.setTitle(_translate("Dialog", "CONFISION MATRİX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Model Eğitim Sonuc"))
        self.groupBox.setTitle(_translate("Dialog", "Grid/Random Search"))
        self.pushButton_7.setText(_translate("Dialog", "Grid Search"))
        self.pushButton_11.setText(_translate("Dialog", "Random Search"))
        self.label_38.setText(_translate("Dialog", "Grid Search İçin Algoritma Seç"))
        self.label_20.setText(_translate("Dialog", "Random İçin Algoritma Seç"))
        self.groupBox_3.setTitle(_translate("Dialog", "Toplu Öğrenme "))
        self.label_11.setText(_translate("Dialog", "Toplu Öğrenme Modeli Seç"))
        self.pushButton_12.setText(_translate("Dialog", "Sonuç Göster"))
        self.label_19.setText(_translate("Dialog", "Başarı Oranı"))
        self.label_45.setText(_translate("Dialog", "R2"))
        self.label_46.setText(_translate("Dialog", "MSE"))
        self.label_47.setText(_translate("Dialog", "MAE"))
        self.groupBox_6.setTitle(_translate("Dialog", "ROC EGRİSİ"))
        self.groupBox_7.setTitle(_translate("Dialog", "CONFISION MATRİX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Grid/Random/Toplu Öğrenme"))
        self.groupBox_4.setTitle(_translate("Dialog", "Yapay Sinir Ağları"))
        self.pushButton_13.setText(_translate("Dialog", "Modeli Eğit"))
        self.label_21.setText(_translate("Dialog", "Epoch Gir"))
        self.label_22.setText(_translate("Dialog", "Başarı Oranı"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Yapay Sinir Ağları"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

